const miscDataRecord = require("d2data/misc.json") as Record<string, MiscData>;

export const getMiscDataFromId = (id: string): MiscData => {
    return miscDataRecord[id];
};

export interface MiscData {
    name: string;
    "*name": string;
    code: string;
    alternategfx: string;
    namestr: string;
    flippyfile: string;
    invfile: string;
    TMogType: string;
    type: string;
    dropsound: string;
    usesound: string;
    state: string;
    stat1: string;
    BetterGem: string;
    NightmareUpgrade: string;
    HellUpgrade: string;
    compactsave: number;
    rarity: number;
    spawnable: number;
    nodurability: number;
    cost: number;
    component: number;
    invwidth: number;
    invheight: number;
    useable: number;
    dropsfxframe: number;
    transtbl: number;
    belt: number;
    spellicon: number;
    pSpell: number;
    len: number;
    calc1: number;
    CharsiMagicLvl: number;
    GheedMagicLvl: number;
    AkaraMin: number;
    AkaraMax: number;
    AkaraMagicLvl: number;
    FaraMagicLvl: number;
    LysanderMin: number;
    LysanderMax: number;
    LysanderMagicMin: number;
    LysanderMagicMax: number;
    LysanderMagicLvl: number;
    DrognanMagicLvl: number;
    HraltiMagicLvl: number;
    AlkorMin: number;
    AlkorMax: number;
    AlkorMagicLvl: number;
    OrmusMagicLvl: number;
    ElzixMagicLvl: number;
    AshearaMagicLvl: number;
    CainMin: number;
    CainMax: number;
    CainMagicLvl: number;
    HalbuMagicLvl: number;
    MalahMin: number;
    MalahMax: number;
    MalahMagicLvl: number;
    LarzukMagicLvl: number;
    DrehyaMagicLvl: number;
    JamellaMin: number;
    JamellaMax: number;
    JamellaMagicLvl: number;
    PermStoreItem: number;
    multibuy: number;
}
